### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by 7ynstar** [feiin/koa-web-template#1]
操作系统：`Windows 11`

Node 版本：`v16.16.0`

执行的命令：`npm run dev`

结果：
![image](https://user-images.githubusercontent.com/56987703/209468961-80f0eb71-3ea1-461d-a71b-b82c2f63b918.png)

**Comment by yangyin5127** [comment]
npm i 安装了依赖没 @7ynstar   不过倒也没再windows下试过 没win环境.

**Comment by 7ynstar** [comment]
> npm i 安装了依赖没 @7ynstar 不过倒也没再windows下试过 没win环境.

依赖安装了，不然运行就是别的提示了，win 下运行不起来

**Comment by yangyin5127** [comment]
回头我找个win试试 看看什么问题

**Comment by yangyin5127** [comment]
@7ynstar  我晓得问题了 windows下管道方式运行有点问题,  你打开package.json 改成`    "dev": "cross-env NODE_ENV=development node ./dev.js |  bunyan"`, 然后全局安装 npm i -g bunyan
